; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


;在配置文件中分号开头为注释
[platformio]
;将源代码的编译目录移到项目目录下，否则默认src下
src_dir = ./

include_dir = core/Inc

[env:genericSTM32F407VGT6]
;配置平台和板子
platform = ststm32
board = genericSTM32F407VGT6
;framework = stm32cube（不用framework了）
;编译配置-D是宏定义，-Idir是include文件目录,读者可按自己项目结构更改
build_flags =         
  -D STM32F407xx
  -ICore/Inc
  -IDrivers/CMSIS/Include
  -IDrivers/CMSIS/Device/ST/STM32F4xx/Include
  -IDrivers/STM32F4xx_HAL_Driver/Inc
  -IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy
  -IMiddlewares/Third_Party/FreeRTOS/Source  
  -IMiddlewares/Third_Party/FreeRTOS/Source/include
  -IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
  -IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
  -IMiddlewares/Third_Party/FreeRTOS/Source/portable/MemMang
  -IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS
  -IMiddlewares/Third_Party/LwIP/system/OS
  -IMiddlewares/Third_Party/LwIP/src/api
  -IMiddlewares/Third_Party/LwIP/src/apps/mqtt
  -IMiddlewares/Third_Party/LwIP/src/core
  -IMiddlewares/Third_Party/LwIP/src/core/ipv4
  -IMiddlewares/Third_Party/LwIP/src/core/ipv6
  -IMiddlewares/Third_Party/LwIP/src/netif
  -IMiddlewares/Third_Party/LwIP/src/netif/ppp
  -ISource/App
  -ISource/Common
  -ISource/Devices
  -ISource/Electronic
  -ISource/Internet/Application
  -ISource/Internet/W5500
  -ISource/Module
  -ISource/SCMD/App
  -ISource/SCMD/Core
  -ISource/StdPort
  -ISource/uLWIP
 

  -mthumb -mfpu=fpv4-sp-d16
  -mfloat-abi=softfp
  -Wl,-u_printf_float 
  ;-wl,-u,_printf_float,_u,_scanf_float
  


;选择编译文件的所在路径，这里包含了源文件路径，启动文件，驱动库和rtos路径。如果+<*>便是路径下的所以文件，-<.git/>便是忽略.git路径下的文件
build_src_filter = 
  +<Core/Src>
  +<iCore> 
  +<startup_stm32f407xx.S>
  +<Drivers/>
  +<Middlewares/>
  +<Source/>
	  -<Source/SCMD/App/scmd_adc.c>
	  -<Source/SCMD/App/scmd_dac.c>
	  -<Source/StdPort/std_adc.c>
	  -<Source/StdPort/std_dac.c>
	  -<Source/StdPort/std_capture.c>
	  -<Source/StdPort/std_pwm.c>
	  -<Source/SCMD/App/scmd_pwm.c>
	  -<Source/SCMD/App/scmd_capture.c>

;选择链接文件
board_build.ldscript = ./STM32F407VGTx_FLASH.ld
;选择下载的仿真器，这里是选择的jlink，如果不设置默认stlink
upload_protocol = stlink
;字面意思
debug_tool = stlink
